- name: NGINX installation and configuration
  hosts: web
  become: true
  tasks:
    - name: apt update cache
      apt:
        update_cache: yes

    - name: install nginx
      apt:
        name: nginx
        state: present
