all:
    children:
        web-servers:
            hosts:
                web1:
                    ansible_host: 127.0.0.1
                    ansible_user: vagrant
                    ansible_port: 2222
                    ansible_ssh_private_key_file: /root/DevOps_Certification/vagrant/vbox-environment-simple/.vagrant/machines/default/virtualbox/private_key


